@TestOn('vm')
library;

import 'dart:collection';
import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:jose_plus/jose.dart';
import 'package:oidc_core/oidc_core.dart';
import 'package:test/test.dart';

/// Independent RFC 7638 §3 thumbprint over an already-canonical (required
/// members only) JWK map: lexicographically sorted, no whitespace, SHA-256,
/// base64url no-pad.
String _independentThumbprint(Map<String, dynamic> jwk) {
  final canonical = jsonEncode(SplayTreeMap<String, dynamic>.of(jwk));
  return base64Url
      .encode(sha256.convert(utf8.encode(canonical)).bytes)
      .replaceAll('=', '');
}

void main() {
  // The padding bug only surfaced for KEYS GENERATED by jose_plus (which emit
  // padded base64), not for the hard-coded unpadded RFC 7638 test vector — so
  // exercise generated keys here.
  group('DPoP canonical JWK / thumbprint (RFC 7638 / RFC 9449 §4.2)', () {
    for (final alg in ['ES256', 'ES384', 'ES512', 'RS256']) {
      test('$alg: embedded jwk + thumbprint are unpadded url-safe base64', () {
        // Several keys: a left-padded short EC coordinate (~1/128) and full-
        // length ones must BOTH come out unpadded and full-length.
        for (var i = 0; i < 8; i++) {
          final key = JsonWebKey.generate(alg);
          final jwk = oidcDPoPPublicJwk(key);
          for (final entry in jwk.entries) {
            final v = entry.value;
            if (v is String) {
              expect(
                v.contains('=') || v.contains('+') || v.contains('/'),
                isFalse,
                reason: '$alg jwk member ${entry.key} must be unpadded url-safe '
                    'base64 (was "$v")',
              );
            }
          }
          final thumbprint = oidcJwkThumbprint(key);
          expect(thumbprint.contains('='), isFalse);
          expect(thumbprint.length, 43, reason: 'SHA-256 b64url no-pad');
          // The thumbprint MUST equal an independent RFC 7638 computation over
          // the (canonical, unpadded) members — i.e. what a compliant server
          // derives. Before the fix these diverged for generated keys.
          expect(thumbprint, _independentThumbprint(jwk));
        }
      });
    }

    test('EC coordinates are normalized to full curve length (P-256 = 32)', () {
      for (var i = 0; i < 50; i++) {
        final jwk = oidcDPoPPublicJwk(JsonWebKey.generate('ES256'));
        for (final member in ['x', 'y']) {
          final bytes = base64Url.decode(
            base64Url.normalize(jwk[member] as String),
          );
          expect(bytes.length, 32, reason: 'P-256 $member must be 32 octets');
        }
      }
    });
  });
}
