version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_core"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_loopback_listener"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/oidc_windows"
    schedule:
      interval: "daily"