// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class OidcNativePigeonCodecReader: FlutterStandardReader {
}

private class OidcNativePigeonCodecWriter: FlutterStandardWriter {
}

private class OidcNativePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return OidcNativePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return OidcNativePigeonCodecWriter(data: data)
  }
}

class OidcNativePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = OidcNativePigeonCodec(readerWriter: OidcNativePigeonCodecReaderWriter())
}

var oidcNativePigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: OidcNativePigeonCodecReaderWriter());


/// Android Custom Tabs / Auth Tab host API (implemented by `oidc_android`).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OidcAndroidHostApi {
  /// Opens the authorization URL and returns the captured redirect URI string
  /// (null when the user cancelled).
  func authorize(url: String, redirectUri: String?, callbackScheme: String?, options: [String: Any?], completion: @escaping (Result<String?, Error>) -> Void)
  /// Opens the end-session URL and returns the captured redirect URI string.
  func endSession(url: String, redirectUri: String?, callbackScheme: String?, options: [String: Any?], completion: @escaping (Result<String?, Error>) -> Void)
  /// Cancels any in-flight native session.
  func cancel() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OidcAndroidHostApiSetup {
  static var codec: FlutterStandardMessageCodec { OidcNativePigeonCodec.shared }
  /// Sets up an instance of `OidcAndroidHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OidcAndroidHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Opens the authorization URL and returns the captured redirect URI string
    /// (null when the user cancelled).
    let authorizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oidc_platform_interface.OidcAndroidHostApi.authorize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let redirectUriArg: String? = nilOrValue(args[1])
        let callbackSchemeArg: String? = nilOrValue(args[2])
        let optionsArg = args[3] as! [String: Any?]
        api.authorize(url: urlArg, redirectUri: redirectUriArg, callbackScheme: callbackSchemeArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizeChannel.setMessageHandler(nil)
    }
    /// Opens the end-session URL and returns the captured redirect URI string.
    let endSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oidc_platform_interface.OidcAndroidHostApi.endSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let redirectUriArg: String? = nilOrValue(args[1])
        let callbackSchemeArg: String? = nilOrValue(args[2])
        let optionsArg = args[3] as! [String: Any?]
        api.endSession(url: urlArg, redirectUri: redirectUriArg, callbackScheme: callbackSchemeArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      endSessionChannel.setMessageHandler(nil)
    }
    /// Cancels any in-flight native session.
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oidc_platform_interface.OidcAndroidHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { _, reply in
        do {
          try api.cancel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}
/// iOS / macOS `ASWebAuthenticationSession` host API (implemented by
/// `oidc_ios` and `oidc_macos`; only one is active at runtime, so they share
/// the API channel name).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OidcAppleHostApi {
  func authorizeApple(url: String, redirectUri: String?, callbackScheme: String?, preferEphemeral: Bool, options: [String: Any?], completion: @escaping (Result<String?, Error>) -> Void)
  func endSessionApple(url: String, redirectUri: String?, callbackScheme: String?, preferEphemeral: Bool, options: [String: Any?], completion: @escaping (Result<String?, Error>) -> Void)
  func cancelApple() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OidcAppleHostApiSetup {
  static var codec: FlutterStandardMessageCodec { OidcNativePigeonCodec.shared }
  /// Sets up an instance of `OidcAppleHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OidcAppleHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let authorizeAppleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oidc_platform_interface.OidcAppleHostApi.authorizeApple\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizeAppleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let redirectUriArg: String? = nilOrValue(args[1])
        let callbackSchemeArg: String? = nilOrValue(args[2])
        let preferEphemeralArg = args[3] as! Bool
        let optionsArg = args[4] as! [String: Any?]
        api.authorizeApple(url: urlArg, redirectUri: redirectUriArg, callbackScheme: callbackSchemeArg, preferEphemeral: preferEphemeralArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authorizeAppleChannel.setMessageHandler(nil)
    }
    let endSessionAppleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oidc_platform_interface.OidcAppleHostApi.endSessionApple\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endSessionAppleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let redirectUriArg: String? = nilOrValue(args[1])
        let callbackSchemeArg: String? = nilOrValue(args[2])
        let preferEphemeralArg = args[3] as! Bool
        let optionsArg = args[4] as! [String: Any?]
        api.endSessionApple(url: urlArg, redirectUri: redirectUriArg, callbackScheme: callbackSchemeArg, preferEphemeral: preferEphemeralArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      endSessionAppleChannel.setMessageHandler(nil)
    }
    let cancelAppleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.oidc_platform_interface.OidcAppleHostApi.cancelApple\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAppleChannel.setMessageHandler { _, reply in
        do {
          try api.cancelApple()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelAppleChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Native browser observability event stream. The native side streams event
/// maps (parsed Dart-side via `OidcNativeBrowserEvent.fromMap`). Only one
/// platform is active at a time, so a single event channel is unambiguous.
class StreamNativeEventsStreamHandler: PigeonEventChannelWrapper<[String: Any?]> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamNativeEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.oidc_platform_interface.OidcNativeEventApi.streamNativeEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<[String: Any?]>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: oidcNativePigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
