version: '3'
services:
  oidc-server-mock:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:      
      - '10154:80' # http port      
      - '10156:443' # https port
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: oidc-server-mock-pwd
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      SERVER_OPTIONS_PATH: /config/server-options.json
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      API_RESOURCES_PATH: /config/api-resources.yaml      
      API_SCOPES_INLINE: |
        - Name: some-app-scope-1
          UserClaims:
            - some-app-scope-1-custom-user-claim
        - Name: some-app-scope-2      
      USERS_CONFIGURATION_PATH: /config/users.yaml
      CLIENTS_CONFIGURATION_PATH: /config/clients.json
      IDENTITY_RESOURCES_PATH: /config/identity-resources.json
      ASPNET_SERVICES_OPTIONS_INLINE: |
        { 
          "BasePath": "/some-base-path",
          "ForwardedHeadersOptions": { 
            "ForwardedHeaders" : "All"
          }
        }
    volumes:
      - ./e2e/config:/config:ro
      - ./e2e/https:/https:ro