version: '3'
services:
  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: ahmednfwela/ory-hydra-auto-login:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
  hydra:
    image: oryd/hydra:v2.3.0
    ports:
      - '4444:4444'
      - '4445:4445'
    command: ["serve", "all", "--dev"]    
    pull_policy: missing
    healthcheck:
      test: "printf 'GET /health/alive HTTP/1.1\r\nHost: localhost\r\n\r\n' | nc localhost 4444 | sed -n '1,/^\r$/d; p' | grep -q '^{\"status\":\"ok\"}$'"
      interval: 5s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    environment:
      DSN: memory
      URLS_SELF_ISSUER: http://localhost:4444
      URLS_LOGIN: http://localhost:3000/login
      URLS_CONSENT: http://localhost:3000/consent
      SECRETS_SYSTEM: some-super-secret
      LOG_LEAK_SENSITIVE_VALUES: 'true'

  hydra-client:
    image: oryd/hydra:v2.3.0
    depends_on:
      hydra:
        condition: service_healthy
    command:
      [
        "create", "client",
        "--endpoint", "http://hydra:4445",
        "--format", "json",
        "--id", "integration-client",
        "--secret", "integration-client-secret",
        "--grant-type", "authorization_code",
        "--token-endpoint-auth-method", "none",
        "--response-type", "code",
        "--skip-consent",
        "--skip-logout-consent",
        "--scope", "openid,profile,email,offline_access",
        "--redirect-uri", "http://localhost:22433/redirect.html,http://127.0.0.1,http://localhost,com.bdayadev.oidc.example:/oauth2redirect",
        "--post-logout-callback", "http://localhost:22433/redirect.html,http://127.0.0.1,http://localhost,com.bdayadev.oidc.example:/endsessionredirect",
        "--request-uri", "http://localhost:22433/redirect.html",
        "--skip-tls-verify"
      ]
    entrypoint: ["hydra"]
    restart: "no"