name: oidc
packages:
  - packages/*
scripts:
  pana:
    run: melos exec -c 1 "pana"
    description: Run pana on all the projects
  generate:dart:
    run: melos exec -c 1 --depends-on="build_runner" --no-flutter -- "dart run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Dart packages in this project.