// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.bdayadev.oidc

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object OidcNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class OidcNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

val OidcNativePigeonMethodCodec = StandardMethodCodec(OidcNativePigeonCodec())


/**
 * Android Custom Tabs / Auth Tab host API (implemented by `oidc_android`).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface OidcAndroidHostApi {
  /**
   * Opens the authorization URL and returns the captured redirect URI string
   * (null when the user cancelled).
   */
  fun authorize(url: String, redirectUri: String?, callbackScheme: String?, options: Map<String, Any?>, callback: (Result<String?>) -> Unit)
  /** Opens the end-session URL and returns the captured redirect URI string. */
  fun endSession(url: String, redirectUri: String?, callbackScheme: String?, options: Map<String, Any?>, callback: (Result<String?>) -> Unit)
  /** Cancels any in-flight native session. */
  fun cancel()

  companion object {
    /** The codec used by OidcAndroidHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      OidcNativePigeonCodec()
    }
    /** Sets up an instance of `OidcAndroidHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OidcAndroidHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oidc_platform_interface.OidcAndroidHostApi.authorize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val redirectUriArg = args[1] as String?
            val callbackSchemeArg = args[2] as String?
            val optionsArg = args[3] as Map<String, Any?>
            api.authorize(urlArg, redirectUriArg, callbackSchemeArg, optionsArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OidcNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OidcNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oidc_platform_interface.OidcAndroidHostApi.endSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val redirectUriArg = args[1] as String?
            val callbackSchemeArg = args[2] as String?
            val optionsArg = args[3] as Map<String, Any?>
            api.endSession(urlArg, redirectUriArg, callbackSchemeArg, optionsArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OidcNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OidcNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oidc_platform_interface.OidcAndroidHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancel()
              listOf(null)
            } catch (exception: Throwable) {
              OidcNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * iOS / macOS `ASWebAuthenticationSession` host API (implemented by
 * `oidc_ios` and `oidc_macos`; only one is active at runtime, so they share
 * the API channel name).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface OidcAppleHostApi {
  fun authorizeApple(url: String, redirectUri: String?, callbackScheme: String?, preferEphemeral: Boolean, options: Map<String, Any?>, callback: (Result<String?>) -> Unit)
  fun endSessionApple(url: String, redirectUri: String?, callbackScheme: String?, preferEphemeral: Boolean, options: Map<String, Any?>, callback: (Result<String?>) -> Unit)
  fun cancelApple()

  companion object {
    /** The codec used by OidcAppleHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      OidcNativePigeonCodec()
    }
    /** Sets up an instance of `OidcAppleHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OidcAppleHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oidc_platform_interface.OidcAppleHostApi.authorizeApple$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val redirectUriArg = args[1] as String?
            val callbackSchemeArg = args[2] as String?
            val preferEphemeralArg = args[3] as Boolean
            val optionsArg = args[4] as Map<String, Any?>
            api.authorizeApple(urlArg, redirectUriArg, callbackSchemeArg, preferEphemeralArg, optionsArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OidcNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OidcNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oidc_platform_interface.OidcAppleHostApi.endSessionApple$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val redirectUriArg = args[1] as String?
            val callbackSchemeArg = args[2] as String?
            val preferEphemeralArg = args[3] as Boolean
            val optionsArg = args[4] as Map<String, Any?>
            api.endSessionApple(urlArg, redirectUriArg, callbackSchemeArg, preferEphemeralArg, optionsArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OidcNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OidcNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oidc_platform_interface.OidcAppleHostApi.cancelApple$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelApple()
              listOf(null)
            } catch (exception: Throwable) {
              OidcNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class OidcNativePigeonStreamHandler<T>(
    val wrapper: OidcNativePigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface OidcNativePigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * Native browser observability event stream. The native side streams event
 * maps (parsed Dart-side via `OidcNativeBrowserEvent.fromMap`). Only one
 * platform is active at a time, so a single event channel is unambiguous.
 */
abstract class StreamNativeEventsStreamHandler : OidcNativePigeonEventChannelWrapper<Map<String, Any?>> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamNativeEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.oidc_platform_interface.OidcNativeEventApi.streamNativeEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = OidcNativePigeonStreamHandler<Map<String, Any?>>(streamHandler)
      EventChannel(messenger, channelName, OidcNativePigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from OidcNativePigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<Map<String, Any?>>) {}

override fun onCancel(p0: Any?) {}
}
      
