name: oidc_linux
description: Linux implementation of the oidc plugin
version: 0.3.0+1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_linux

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      linux:
        pluginClass: OidcPlugin
        dartPluginClass: OidcLinux

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  oidc_core: ^0.4.0+1  
  oidc_desktop: ^0.2.0+1
  oidc_platform_interface: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
