name: oidc_linux
description: Linux implementation of the oidc plugin
version: 0.3.0+13
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_linux
homepage: https://bdaya-dev.github.io/oidc/
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      linux:
        pluginClass: OidcPlugin
        dartPluginClass: OidcLinux

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  oidc_core: ^0.10.0  
  oidc_desktop: ^0.5.0+2
  oidc_platform_interface: ^0.6.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=5.0.0 <8.0.0"
