name: "Set up Integration test"
description: "Sets up the environment for Flutter integration tests"

inputs:
  channel:
    description: "Flutter channel to use"
    default: "stable"
  flutter-version:
    description: "Flutter version to use"
    default: "3.22.0"

runs:
  using: "composite"
  steps:
    - name: Set up Environment
      uses: ./.github/actions/flutter_base
      with:
        channel: ${{ inputs.channel }}
        flutter-version: ${{ inputs.flutter-version }}

    - name: Remove dart_test.yaml Files
      run: dart run melos run remove_dart_test_yaml
      shell: bash

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1

    - name: Start Ory Hydra
      run: docker compose up -d
      shell: bash
      # uses: hoverkraft-tech/compose-action@v2.2.0
      # with:
      #   compose-file: "./docker-compose.yaml"