name: oidc_example_android
description: Demonstrates how to use the oidc plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0
  bdaya_shared_value: ^3.1.3
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  logging: ^1.2.0
  oidc_android:
    path: ../
  oidc_core: ^0.9.1
  oidc_default_store: ^0.2.0+12
  oidc_platform_interface: ^0.6.0+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
