include: package:very_good_analysis/analysis_options.5.0.0.yaml

linter:
  rules:
    always_use_package_imports: false
    sort_pub_dependencies: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
analyzer:
  errors:
    invalid_use_of_internal_member: ignore
