name: oidc
description: A comprehensive OpenIdConnect plugin that works on all platforms (android, ios, windows, linux, web, macos)
version: 0.3.1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc
topics: ['oidc', 'openidconnect', 'oauth', 'authentication']

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"
flutter:
  plugin:
    platforms:
      android:
        default_package: oidc_android
      ios:
        default_package: oidc_ios
      linux:
        default_package: oidc_linux
      macos:
        default_package: oidc_macos
      web:
        default_package: oidc_web
      windows:
        default_package: oidc_windows

dependencies:
  flutter:
    sdk: flutter
  # Endorsed packages
  oidc_android: ^0.3.0+2
  oidc_core: ^0.4.1
  oidc_ios: ^0.3.0+2
  oidc_linux: ^0.3.0+2
  oidc_macos: ^0.3.0+2
  oidc_platform_interface: ^0.3.0+2
  oidc_web: ^0.3.0+2
  oidc_windows: ^0.3.0+2
  # ====================
  http: ^1.1.0
  jose_plus: ^0.4.1
  retry: ^3.1.2
  rxdart: ^0.27.7
  logging: ^1.2.0
  json_annotation: ^4.8.1
  nonce: ^1.2.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
