name: oidc
description: A comprehensive OpenIdConnect package
version: 0.2.0
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"
flutter:
  plugin:
    platforms:
      android:
        default_package: oidc_android
      ios:
        default_package: oidc_ios
      linux:
        default_package: oidc_linux
      macos:
        default_package: oidc_macos
      web:
        default_package: oidc_web
      windows:
        default_package: oidc_windows

dependencies:
  flutter:
    sdk: flutter
  # Endorsed packages
  oidc_android: ^0.2.0
  oidc_core: ^0.3.0
  oidc_ios: ^0.2.0
  oidc_linux: ^0.2.0
  oidc_macos: ^0.2.0
  oidc_platform_interface: ^0.1.0+2
  oidc_web: ^0.2.0
  oidc_windows: ^0.2.0
  # ====================
  http: ^1.1.0
  jose: ^0.3.4
  retry: ^3.1.2
  rxdart: ^0.27.7
  logging: ^1.2.0
  json_annotation: ^4.8.1
  nonce: ^1.2.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
