name: oidc
description: A comprehensive OpenIdConnect plugin that works on all platforms (android, ios, windows, linux, web, macos)
version: 0.12.2
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc
topics: ['oidc', 'openidconnect', 'oauth', 'authentication']
homepage: https://bdaya-dev.github.io/oidc/
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"
flutter:
  plugin:
    platforms:
      android:
        default_package: oidc_android
      ios:
        default_package: oidc_ios
      linux:
        default_package: oidc_linux
      macos:
        default_package: oidc_macos
      web:
        default_package: oidc_web
      windows:
        default_package: oidc_windows

dependencies:
  flutter:
    sdk: flutter
  # Endorsed packages
  oidc_android: ^0.7.0+6
  oidc_core: ^0.14.2+2
  oidc_ios: ^0.7.0+6
  oidc_linux: ^0.4.1+3
  oidc_macos: ^0.7.0+6
  oidc_platform_interface: ^0.6.0+10
  oidc_web: ^0.6.0+10
  oidc_windows: ^0.3.1+15
  # ====================
  http: ^1.1.0
  jose_plus: ^0.4.4
  retry: ^3.1.2
  rxdart: ">=0.27.7 <2.0.0"
  logging: ^1.2.0
  json_annotation: ^4.8.1
  nonce: ^1.2.0
  uuid: ^4.0.0
  clock: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.6
  collection: ^1.17.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ">=5.0.0 <9.0.0"
