include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    sort_pub_dependencies: ignore
    deprecated_member_use_from_same_package: ignore
    # invalid_dependency: ignore

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    require_trailing_commas: false
    always_use_package_imports: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    # deprecated_member_use_from_same_package: false
# Uncomment the following section to specify additional rules.

# linter:
#   rules:
#     - camel_case_types

# analyzer:
#   exclude:
#     - path/to/excluded/files/**

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
