name: oidc_core
description: A dart package containing models and helpers for OpenId Connect spec.
version: 0.9.1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_core
topics: ['oidc', 'openidconnect', 'oauth', 'authentication']
homepage: https://bdaya-dev.github.io/oidc/
environment:
  sdk: ^3.1.0

dependencies:
  crypto: ^3.0.3
  jose_plus: ^0.4.4
  http: ^1.1.0
  json_annotation: ^4.9.0
  uuid: "^4.0.0"
  meta: ^1.9.1
  nonce: ^1.2.0
  logging: ^1.2.0
  clock: ^1.1.1
  copy_with_extension: ^5.0.4
  rxdart: ">=0.27.7 <2.0.0"

dev_dependencies:
  build_runner: ^2.4.6
  lints: ">=2.0.0 <6.0.0"
  test: ^1.21.0
  very_good_analysis: ">=5.0.0+1 <8.0.0"
  json_serializable: ^6.7.1
  collection: ^1.18.0
  fake_async: ^1.3.1
  oidc_loopback_listener: ^0.2.0
  copy_with_extension_gen: ^5.0.4
