name: oidc_core
description: A dart package containing classes and helpers for OpenIdConnect v1.0
version: 1.0.0
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_core

environment:
  sdk: ^3.1.0

dependencies:
  http: ^1.1.0
  jose: ^0.3.4
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: 6.7.1
  build_runner: ^2.4.6
  