name: oidc_core
description: A dart package containing classes and helpers for OpenIdConnect v1.0
version: 0.4.0+1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_core
topics: ['oidc', 'openidconnect', 'oauth', 'authentication']
environment:
  sdk: ^3.1.0

dependencies:
  crypto: ^3.0.3
  jose_plus: ^0.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  uuid: "^4.0.0"
  meta: ^1.9.1
  nonce: ^1.2.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
  json_serializable: ^6.7.1
  collection: ^1.18.0
