name: oidc_core
description: A dart package containing classes and helpers for OpenIdConnect v1.0
version: 0.1.0+1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_core
topics: ['oidc', 'openidconnect', 'oauth', 'authentication']
environment:
  sdk: ^3.1.0

dependencies:
  
  crypto: ^3.0.3
  http: ^1.1.0
  json_annotation: ^4.8.1
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
