name: oidc_example_web
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0
resolution: workspace
environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  oidc_web:
    path: ../

flutter:
  uses-material-design: true

