name: oidc_loopback_listener
description: A server that listens on loopback address for an authorization response
version: 0.2.0
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_loopback_listener
homepage: https://bdaya-dev.github.io/oidc/
environment:
  sdk: ">=3.1.0 <4.0.0"  
dependencies:
  meta: ^1.9.1

dev_dependencies:
  http: ^1.1.0
  mocktail: ">=0.3.0 <2.0.0"
  test: ^1.19.2
  very_good_analysis: ">=5.0.0 <7.0.0"
