on: workflow_call
jobs:
  hydra-setup:
    runs-on: ubuntu-latest
    services:
      hydra:
        image: oryd/hydra:v2.3.0
        env:
          DSN: memory
          URLS_SELF_ISSUER: http://localhost:4444
          URLS_LOGIN: http://localhost:3000/login
          URLS_CONSENT: http://localhost:3000/consent
          SECRETS_SYSTEM: some-super-secret
          LOG_LEAK_SENSITIVE_VALUES: 'true'
          DEV: 'true'

      consent:
        image: ahmednfwela/ory-hydra-auto-login:latest
        ports:
          - 3000:3000
        env:
          HYDRA_ADMIN_URL: http://hydra:4445
    steps:

      - run: docker ps -a
        name: List all containers
      - name: Wait for Hydra → alive
        run: |
          for i in {1..10}; do
            if curl -sf http://hydra:4444/health/alive; then
              echo "✅ hydra is up"; break
            fi
            echo "⏳ waiting for hydra…"; sleep 5
          done

      # Now run the one‑off client creation
      - name: Create Hydra client
        run: |
          # you can either use the hydra CLI if it's installed,
          # or spin up a transient container:
          docker run --rm \
            --network host \
            oryd/hydra:v2.3.0 create client \
              --endpoint http://localhost:4445 \
              --format json \
              --id integration-client \
              --secret integration-client-secret \
              --grant-type authorization_code \
              --token-endpoint-auth-method none \
              --response-type code \
              --skip-consent \
              --skip-logout-consent \
              --scope openid,profile,email,offline_access \
              --redirect-uri http://localhost:22433/redirect.html,http://127.0.0.1,http://localhost,com.bdayadev.oidc.example:/oauth2redirect \
              --post-logout-callback http://localhost:22433/redirect.html,http://127.0.0.1,http://localhost,com.bdayadev.oidc.example:/endsessionredirect \
              --request-uri http://localhost:22433/redirect.html \
              --skip-tls-verify