name: oidc_platform_interface

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/oidc_core.yaml"
      - "packages/oidc_core/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/oidc_core.yaml"
      - "packages/oidc_core/**"

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: pushd e2e-tests && docker-compose up -d --build && popd

  build:
    needs: docker
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1    
    with:
      dart_sdk: 3.1.0
      working_directory: packages/oidc_core
      min_coverage: 20

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      min_score: 100

