name: oidc_web

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/oidc_web.yaml"
      - "packages/oidc_web/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/oidc_web.yaml"
      - "packages/oidc_web/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.13.1
      working_directory: packages/oidc_web

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      min_score: 100

