name: oidc_loopback_listener

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/oidc_loopback_listener.yaml"
      - "packages/oidc_loopback_listener/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/oidc_loopback_listener.yaml"
      - "packages/oidc_loopback_listener/**"

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      min_coverage: 0
      working_directory: packages/oidc_loopback_listener

  pana:
    uses: ./.github/workflows/pana.yaml
    needs: build
    with:
      min_score: 100

