name: oidc_linux

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/oidc_linux.yaml"
      - "oidc_linux/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/oidc_linux.yaml"
      - "oidc_linux/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.10.0
      working_directory: oidc_linux

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1

