name: oidc_web

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/oidc_web.yaml"
      - "packages/oidc_web/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/oidc_web.yaml"
      - "packages/oidc_web/**"

jobs:
  build:
    uses: ./.github/workflows/base/flutter_package.yaml
    with:
      working_directory: packages/oidc_web

  pana:
    uses: ./.github/workflows/base/pana.yaml
    with:
      min_score: 100

