name: oidc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - main

jobs:

  build:
    uses: ./.github/workflows/flutter_package.yaml
    with:
      working_directory: packages/oidc

  pana:
    uses: ./.github/workflows/pana.yaml
    with:
      min_score: 100


  android:
    runs-on: macos-latest
    if: false # TODO: Integration tests are flaky, see https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/issues/79

    defaults:
      run:
        working-directory: packages/oidc/example

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Melos
        uses: bluefireteam/melos-action@v3

      - name: AVD Cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter test integration_test
          working-directory: packages/oidc/example

  ios:
    runs-on: macos-latest
    # disable ios due to timeout errors
    if: false    
    defaults:
      run:
        working-directory: packages/oidc/example

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Melos
        uses: bluefireteam/melos-action@v3

      - name: Start Simulator
        # Start an iPhone simulator
        run: |
          UDID=$(xcrun xctrace list devices | grep "^iPhone" | awk '{gsub(/[()]/,""); print $NF}' | head -n 1)
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - name: Integration Tests
        run: flutter test integration_test -d iPhone

  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/oidc/example

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev

      - name: Enable desktop support
        run: flutter config --enable-linux-desktop

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Melos
        uses: bluefireteam/melos-action@v3

      - name: Integration Tests
        run: xvfb-run flutter test integration_test -d linux

  macos:
    runs-on: macos-latest
    if: false # TODO: Macos tests are flaky, see https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/issues/79

    defaults:
      run:
        working-directory: packages/oidc/example

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - name: Enable desktop support
        run: flutter config --enable-macos-desktop
      
      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Melos
        uses: bluefireteam/melos-action@v3
        
      - name: Integration Tests
        run: flutter test integration_test -d macos

  web:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: packages/oidc/example

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Melos
        uses: bluefireteam/melos-action@v3
      
      - name: Run Chromedriver
        uses: nanasess/setup-chromedriver@v2
      - run: chromedriver --port=4444 & sleep 5
          

      # - name: Run Chromedriver
      #   run: |
      #     git clone https://github.com/Bdaya-Dev/web_installers --branch new-chromedriver-urls
      #     cd web_installers/packages/web_drivers
      #     dart pub get
      #     dart lib/web_driver_installer.dart chromedriver &
      #   # ./chromedriver/chromedriver --port=4444 &

      - name: Integration Tests
        run: flutter drive -v --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --browser-name=chrome

  windows:
    runs-on: windows-2019
    # Melos action does not work on windows: https://github.com/bluefireteam/melos-action/issues/5
    if: true 
    defaults:
      run:
        working-directory: packages/oidc/example

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2

      - name: Enable desktop support
        run: flutter config --enable-windows-desktop

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Melos
        uses: bluefireteam/melos-action@v3

      - name: Integration Tests
        run: flutter test integration_test -d windows
