name: Publish packages
on:
  # Enable to also publish, when pushing a tag
  #push:
  #  tags:
  #    - '*'
  workflow_dispatch:

jobs:
  publish-packages:
    name: Publish packages
    permissions:
      contents: write
      id-token: write # Required for authentication using OIDC
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
      - uses: ahmednfwela/melos-action@main
        with:
          run-bootstrap: true
          publish: true